image: node:18

pipelines:
  default:
    - step:
        name: Build and Deploy to S3
        caches:
          - node
        script:
          # 0. .env 파일 생성
          - echo "NEXT_PUBLIC_KAKAO_MAP_KEY=$NEXT_PUBLIC_KAKAO_MAP_KEY" > .env

          # 1. 의존성 설치
          - npm install

          # 2. 빌드
          - rm -rf .next out
          - npm run build
          - npx next export

          # 3. AWS CLI 설치
          - apt-get update && apt-get install -y awscli


          # 4. S3 업로드
          - aws s3 sync out/ s3://$AWS_BUCKET_NAME --delete

          # 5. CloudFront 캐시 무효화
          - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

